function [g_value, h_value] = calculate_next_values_distance(scenario, parent_g_value, last_pose, next_pose)

    g_value_change = euclidean_distance(...
        last_pose.xs, last_pose.ys,...
        next_pose.xs, next_pose.ys...
    );
            
    g_value = parent_g_value + g_value_change;

    h_value = euclidean_distance(...
        next_pose.xs, next_pose.ys...
        [scenario.vehicles(:).x_goal],[scenario.vehicles(:).y_goal]...
    );
    
end

