function yaw = calculate_yaw(refPath)
    % calculate_yaw - Calculates the yaw angle of the reference path

    yaw = zeros(length(refPath), 1);

    dpos = refPath(3:end, :) - refPath(1:end - 2, :);
    yaw(2:end - 1) = atan2(dpos(:, 2), dpos(:, 1));

    yaw(1) = atan2( ...
        refPath(2, 2) - refPath(1, 2), ...
        refPath(2, 1) - refPath(1, 1) ...
    );

    yaw(end) = atan2( ...
        refPath(end, 2) - refPath(end - 1, 2), ...
        refPath(end, 1) - refPath(end - 1, 1) ...
    );

end
