stages:
  - Test

.matlab_defaults:
  image:
    name: registry.git-ce.rwth-aachen.de/cpm/coincar/software/graph_based_planning/matlab:test
    entrypoint: [""]


Startup unittest:
  extends: .matlab_defaults
  stage: Test
  script:
    - matlab -batch "mex -setup C; mex -setup C++; openProject('graph_based_planning.prj')"
  tags:
    - docker

Intersect unittest:
  extends: .matlab_defaults
  stage: Test
  script:
    - matlab -batch "openProject('graph_based_planning.prj'); results = runtests('tests/intersect_unittest.m'); assertSuccess(results);"
  tags:
    - docker

Scenario Unittest:
  extends: .matlab_defaults
  stage: Test
  script:
    - matlab -batch "openProject('graph_based_planning.prj'); results = runtests('tests/scenario_unittest.m'); assertSuccess(results);"
  artifacts:
    paths:
      - results/
    expire_in: 1 week  
  tags:
    - docker

    
