function cols = nodeCols()
    cols = struct(...
        'x',          1 ...
        ,'y',         2 ...
        ,'yaw',       3 ...
        ,'trim',      4 ...
        ,'g',         5 ...
        ,'h',         6 ...
        ,'depth',     7 ...
        ,'exactEval', 8 ...
    );
end