function mixedTrafficOptions = mixedTrafficSelection(vehicle_amount_p,mode_option_p)

scenarios = {
    'No manual vehicle', pi+pi; ...
    '1', pi+pi*(1:2); ...
    '2', pi+2*pi/3*(1:3); ...
    '3', pi+2*pi/4*(1:4); ...
    '4', pi+2*pi/5*(1:5); ...
    '5', pi+2*pi/6*(1:6); ...
    '6', pi+2*pi/7*(1:7); ...
    '7', pi+2*pi/8*(1:8); ...
    '8', pi+2*pi/9*(1:10); ...
    '9', pi+2*pi/10*(1:10); ...
    '10', pi+2*pi/11*(1:11); ...
    '11', pi+2*pi/12*(1:12); ...
    '12', pi+2*pi/13*(1:13); ...
    '13', pi+2*pi/14*(1:14); ...
    '14', pi+2*pi/15*(1:15); ...
    '15', pi+2*pi/15*(1:16); ...
    '16', pi+2*pi/15*(1:17); ...
    '17', pi+2*pi/15*(1:18); ...
    '18', pi+2*pi/15*(1:19); ...
    '19', pi+2*pi/15*(1:20); ...
    '20', pi+2*pi/15*(1:21); ...
    };

    possModes = {
    '1', 'Guided-Mode'; ...
    '2', 'Expert-Mode'; ...
    };

    try
        load([tempdir 'uiMixedTrafficSelection'], 'vehicle_amount', 'mode_option');
    catch
        % continue
    end

if nargin < 1
    if ~exist('vehicle_amount','var')
        vehicle_amount = 1;
    end
    if ~exist('mode_option','var')
        mode_option = 2;
    end

    [vehicle_amount,ok] = listdlg(...
        'ListString',scenarios(:,1), ...
        'ListSize', [300,300], ...
        'SelectionMode', 'single', ...
        'InitialValue', vehicle_amount, ...
        'PromptString', 'Choose the ID of the manual vehicle');

    if(~ok)
        error('Canceled');
    end

    if vehicle_amount ~= 1
        [mode_option,ok] = listdlg(...
            'ListString',possModes(:,2), ...
            'ListSize', [300,300], ...
            'SelectionMode', 'single', ...
            'InitialValue', mode_option, ...
            'PromptString', 'Choose the manual control mode');

        if(~ok)
            error('Canceled');
        end
    end

else
    vehicle_amount = vehicle_amount_p;
    mode_option = mode_option_p;
end

mixedTrafficOptions.id = vehicle_amount;
mixedTrafficOptions.mode = mode_option;

    save([tempdir 'uiMixedTrafficSelection'], 'vehicle_amount', 'mode_option');

end
